-- MySQL Script generated by MySQL Workbench
-- Mon Sep  3 14:52:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema car
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marca` ;

CREATE TABLE IF NOT EXISTS `marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `descripsion` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo` ;

CREATE TABLE IF NOT EXISTS `modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `marca_id` INT NOT NULL,
  `descripsion` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelo_marca1_idx` (`marca_id` ASC),
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clase` ;

CREATE TABLE IF NOT EXISTS `clase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(45) NOT NULL,
  `descripsion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehiculo` ;

CREATE TABLE IF NOT EXISTS `vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `modelo_id` INT NOT NULL,
  `clase_id` INT NOT NULL,
  `matricula` VARCHAR(45) NULL,
  `foto` BLOB NULL,
  `status` VARCHAR(45) NULL,
  `nasientos` VARCHAR(45) NULL,
  `transmision` VARCHAR(45) NULL,
  `cuentaxdia` DECIMAL NULL,
  `cilindrada` INT NULL,
  `anio` INT NULL,
  `descripsion` VARCHAR(255) NULL,
  `combustible` VARCHAR(45) NULL,
  `color` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `placa_UNIQUE` (`matricula` ASC),
  INDEX `fk_vehiculo_modelo1_idx` (`modelo_id` ASC),
  INDEX `fk_vehiculo_clase1_idx` (`clase_id` ASC),
  CONSTRAINT `fk_vehiculo_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_clase1`
    FOREIGN KEY (`clase_id`)
    REFERENCES `clase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `descripsion` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `descripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `descripcion` ;

CREATE TABLE IF NOT EXISTS `descripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `categoria_id` INT NOT NULL,
  `descripsion` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_descripsion_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_descripsion_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dia` ;

CREATE TABLE IF NOT EXISTS `dia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entrada` ;

CREATE TABLE IF NOT EXISTS `entrada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `descripsion_id` INT NOT NULL,
  `dia_id` INT NOT NULL,
  `vehiculo_id` INT NOT NULL,
  `valor` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entrada_descripsion1_idx` (`descripsion_id` ASC),
  INDEX `fk_entrada_vehiculo1_idx` (`vehiculo_id` ASC),
  INDEX `fk_entrada_dia1_idx` (`dia_id` ASC),
  CONSTRAINT `fk_entrada_descripsion1`
    FOREIGN KEY (`descripsion_id`)
    REFERENCES `descripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_dia1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `salida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salida` ;

CREATE TABLE IF NOT EXISTS `salida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `descripsion_id` INT NOT NULL,
  `dia_id` INT NOT NULL,
  `vehiculo_id` INT NOT NULL,
  `valor` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salida_descripsion1_idx` (`descripsion_id` ASC),
  INDEX `fk_salida_dia1_idx` (`dia_id` ASC),
  INDEX `fk_salida_vehiculo1_idx` (`vehiculo_id` ASC),
  CONSTRAINT `fk_salida_descripsion1`
    FOREIGN KEY (`descripsion_id`)
    REFERENCES `descripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salida_dia1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salida_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `conductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conductor` ;

CREATE TABLE IF NOT EXISTS `conductor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `numerodocumento` VARCHAR(45) NULL,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabajo` ;

CREATE TABLE IF NOT EXISTS `trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `vehiculo_id` INT NOT NULL,
  `dia_id` INT NOT NULL,
  `conductor_id` INT NOT NULL,
  `nvueltas` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trabajo_vehiculo1_idx` (`vehiculo_id` ASC),
  INDEX `fk_trabajo_dia1_idx` (`dia_id` ASC),
  INDEX `fk_trabajo_conductor1_idx` (`conductor_id` ASC),
  CONSTRAINT `fk_trabajo_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_dia1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_conductor1`
    FOREIGN KEY (`conductor_id`)
    REFERENCES `conductor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `alquiler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler` ;

CREATE TABLE IF NOT EXISTS `alquiler` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `vehiculo_id` INT NOT NULL,
  `conductor_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `cuentapactada` DECIMAL NULL,
  `fechainicio` DATETIME NULL,
  `fechafin` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehiculochofer_vehiculo1_idx` (`vehiculo_id` ASC),
  INDEX `fk_vehiculochofer_conductor1_idx` (`conductor_id` ASC),
  CONSTRAINT `fk_vehiculochofer_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculochofer_conductor1`
    FOREIGN KEY (`conductor_id`)
    REFERENCES `conductor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cierre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cierre` ;

CREATE TABLE IF NOT EXISTS `cierre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `vehiculo_id` INT NOT NULL,
  `fechainicio` DATE NULL,
  `fechafin` DATE NULL,
  `totalentrada` DECIMAL NULL,
  `totalsalida` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cierre_vehiculo1_idx` (`vehiculo_id` ASC),
  CONSTRAINT `fk_cierre_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rol` ;

CREATE TABLE IF NOT EXISTS `rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateupdated` DATETIME NULL,
  `createdby` VARCHAR(45) NULL,
  `updatedby` VARCHAR(45) NULL,
  `version` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(45) NOT NULL,
  `rol_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_rol1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
